clean-up details page for styling
buildpacks/registry-api pull request #11
Opened 2021-01-28 18:48 UTC by elbandito

Signed-off-by: Travis <longoria.public@gmail.com>

2021-01-28 22:27 UTC, jkutner requested changes

2021-01-28 22:27 UTC, jkutner commented on app/javascript/components/buildpack/Detail.tsx
> +                                    <code>pack build myapp --buildpack {buildpack.latest.ns}/{buildpack.latest.name}</code>
```suggestion
                                    <code>pack build myapp --buildpack {buildpack.latest.namespace}/{buildpack.latest.name}</code>
```

2021-01-28 23:35 UTC, elbandito commented on app/javascript/components/buildpack/Detail.tsx
> +                                    <code>pack build myapp --buildpack {buildpack.latest.ns}/{buildpack.latest.name}</code>
Good catch!

2021-01-29 14:38 UTC, jkutner approved these changes

2021-01-29 16:39 UTC, merged